version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       database:
        condition: service_healthy
    networks:
      - my-diary-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-diary-network

  conversation_api:
    build:
      context: ./conversation_api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database
    networks:
      - my-diary-network


  database:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dev_my_diary
      MYSQL_USER: my_diary_user
      MYSQL_PASSWORD: Mydiary!2025
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-diary-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  db-data:

networks:
  my-diary-network:
    driver: bridge
