version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Spring Boot から DB 接続する際は、接続先ホスト名として「database」を使用する前提です。
    environment:
      SPRING_PROFILES_ACTIVE: development
      # 例：Spring Boot 側で使用する接続情報
      # SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/diary?useSSL=false&serverTimezone=UTC
      # SPRING_DATASOURCE_USERNAME: diaryuser
      # SPRING_DATASOURCE_PASSWORD: diarypass
    depends_on:
      - database

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: diary
      MYSQL_USER: diaryuser
      MYSQL_PASSWORD: diarypass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
