version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       database:
        condition: service_started #db起動時に、appが起動する
    networks:
      - my-diary-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-diary-network


  database:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dev_my_diary
      MYSQL_USER: my_diary_user
      MYSQL_PASSWORD: Mydiary!2025
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-diary-network


volumes:
  db-data:

networks:
  my-diary-network:
    driver: bridge
