CREATE DATABASE IF NOT EXISTS dev_my_diary;

USE dev_my_diary;

CREATE TABLE IF NOT EXISTS users(
id INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(10) NOT NULL,
password VARCHAR(10),
join_date DATE
);

CREATE TABLE IF NOT EXISTS diaries(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
post_date DATETIME,
comment VARCHAR(500),
picture BLOB,
FOREIGN KEY (user_id) REFERENCES users(id)
);
