CREATE DATABASE IF NOT EXISTS dev_my_diary;

USE dev_my_diary;

CREATE TABLE IF NOT EXISTS user(
id INT AUTO_INCREMENT PRIMARY KEY,
password VARCHAR(10),
name VARCHAR(10) NOT NULL
join_date DATE
);

CREATE TABLE IF NOT EXISTS diary(
id INT AUTO_INCREMENT PRIMARY KEY,
FOREIGN KEY (user_id) REFERENCES user(id),
post_date DATETIME,
comment VARCHAR(500),
picture
);
